### PR TITLE
Add support for outside air temperature sensor

### PR DESCRIPTION
**Pull request by miipekk-ihme**
This patch adds a new outside air temperature sensor. Works for my MUZ-RW25VGHZ-SC1 / MSZ-RW25VG-SC1 unit. The sensor seems to have a resolution of 1C.

The sensor needs to be added into the yaml configuration also:
```
climate:
  - platform: cn105
    id: hp
    name: ${friendly_name}
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
    compressor_frequency_sensor:
      name: ${name} Compressor Frequency
    outside_air_temperature_sensor:
      name: ${name} Outside air temperature
    vertical_vane_select:
      name: ${name} Vertical Vane
    horizontal_vane_select:
      name: ${name} Horizontal Vane
    isee_sensor:
      name: ${name} ISEE Sensor
    auto_sub_mode_sensor:
      name: auto-submode sensor
    sub_mode_sensor:
      name: submode sensor
    stage_sensor:
      name: stage sensor
    remote_temperature_timeout: 30min
    debounce_delay : 400ms
    update_interval: 1s
```

### CODE REVIEW

**Comment by MarkoPaasila** [comment]
Just reporting that this doesn't work with the FD25 or LN35.

**Comment by echavet** [comment]
Yes 
It is probably not supported 
But no crash?

**Comment by miipekk-ihme** [comment]
> Just reporting that this doesn't work with the FD25 or LN35.

Thanks for reporting. So it will just report zero? I will release a new patch in upcoming days for the compressor frequency PR after more testing (that could be actually the input power in watts instead of the actual frequency, so a new sensor needs to be created). I have probably also found counters for the total consumed energy in kWh and total operating hours (two new sensors). But these needs more testing, so I try to verify these functions before I will create a new PR.

**Comment by MarkoPaasila** [comment]
No crash :-)
FD25 reports a constant -1 °C
LN35 reports the correct temperature while heating (maybe also other modes), when idle, it falls back to -63.5 °C.

**Comment by jasestu** [comment]
Awesome, thanks for this - always love more data. Working great on my MXZ-4F80VGD outdoor unit. Will try it on the other different models I have in the near future.

**Comment by jasestu** [comment]
| Indoor       | Outdoor      | Temperature                             |
|--------------|--------------|-----------------------------------------|
| MSZ-AP25VGD  | MXZ-4F80VGD  | Works                                   |
| MSZ-AP35VGD  | MUZ-AP35VG   | Works but reports -63.5C when idle        |
| MSZ-AP60VGD  | MUZ-AP60VG   | Works                                   |
| MSZ-AP71VGD  | MUZ-AP71VG   | Works but reports -63.5C when idle        |

**Comment by phidauex** [comment]
Very cool PR! I run calculations to determine my current COP, and have been using the air temperature from my weather station up on the roof - this should be a bit more accurate, and helpful for people wanting to troubleshoot. It seems to generate reasonable values on my MXZ-SM42NAHZ (newer Smart Multi outdoor unit, hyperheat, north america version) when operating and while idle.

I've updated the documentation with the basics for the sensor already. Looking forward to additional sensors you might find, @miipekk-ihme. Input power would be very helpful for COP calculations (if we had this and outside temp then the only other thing you need is the table of COP vs outdoor temp values for the unit).

**Comment by MarkoPaasila** [comment]
> I run calculations to determine my current COP

Am I right that you don't calculate the actual COP but look up the values from the spec sheet based on outside temperature? May I ask what you do with that knowledge? Just interested...

I use the inside unit air volume from the specs, measure enthalpy before and after indoor unit, measure power draw, and calculate COP from there. I do it for fun, but also use it to make sure the unit is working properly.

**Comment by phidauex** [comment]
@MarkoPaasila Good point, yes, I'm doing a lookup of the expected COP given the outdoor temperature, indoor temperature, and power draw of the outdoor unit. Power draw and local outdoor temperature are measured, indoor temperature is assumed based on the mode (heating/cooling), and COP is from the NEEP tested data charts, which I fit to a polynomial.

A future version of my ESPhome device would include two temperature sensors for intake and outlet temp (though I suppose I'd need humidity as well for enthalpy). Fan speed can now be mapped to the specified CFMs using the stage sensor, and if we captured power draw, then we could potentially do all the COP calculations inside the ESP device, which would be quite cool. One tough thing for me is that I have two multi-head outdoor units, and 5 indoor units, so that is a lot of sensors and calculating...

My main use case is to be able to talk more clearly with people about heatpump benefits and savings. Savings "calculators" usually just use a very optimistic nominal COP, but then detractors just look at the worst COP and use that, neither of which give a clear picture. I like being able to show what my real weighted average COP is for a season to compare to natural gas pricing. Plus, numbers are fun.

**Comment by phidauex** [comment]
Thanks, that makes sense. I’m a power engineer by trade, and I’ve really come to appreciate how much of mechanical (and civil) engineering involves just keeping track of where the water is at any given time. 

Unfortunately in this case it looks like my unit doesn’t support the power sensor so my dream will not be realized today, but hopefully another time.

**Pull request merged**
