### PR TITLE
Intuitive vane mappings

### PR DESCRIPTION
**Pull request by SixFive7**
I searched for some supported unicode icons to more intuitively show the vane status. This also aligns horizontal and vertical mappings.

### CODE REVIEW

**Comment by echavet** [comment]
Hi @SixFive7,
I don't know why but your values appear like that:

`static const char* WIDEVANE_MAP[7] = { "⯬", "🠘",  "|",  "🠚",  "⯮", "🠘🠚", "SWING" };`

Apart from this character issue, did you test the component behavior with these values  ?

**Comment by SixFive7** [comment]
> Hi @SixFive7, I don't know why but your values appear like that:
> 
> `static const char* WIDEVANE_MAP[7] = { "⯬", "🠘", "|", "🠚", "⯮", "🠘🠚", "SWING" };`
> 
> Apart from this character issue, did you test the component behavior with these values ?

I'm not sure what you mean with "like that", But I'm assuming the unicode chars are incorrectly rendering for you like in my own email:
image
But on the github website they are rendering just fine:
image

I did test to make sure everything still worked and how these characters appear on the ESP component site and inside home assistant. All seems good.

Firefox:
image
image

Chrome:
image
image

Home assistant on Firefox:
image
image
image

**Comment by echavet** [comment]
Well I did the merge and the result is what I was afraid of:
Capture d’écran 2024-04-24 à 15 33 57

**Comment by SixFive7** [comment]
Ai that is unfortunate. I checked home assistant on the browser and that is fine, but this looks like the app. Haven't tried that one yet. I'll install it and see if compatible characters exists to fix this.

**Comment by echavet** [comment]
Well I don't know what happened with your commit. It looks like mine,
choosing the same characters set, has been successful.
Do you confirm you can read them well in the main branch?


Le sam. 20 avr. 2024, 02:09, Jori Huisman ***@***.***> a
écrit :

**Comment by SixFive7** [comment]
Ha, you chose exactly the same characters as [my new pull request](https://github.com/echavet/MitsubishiCN105ESPHome/pull/80). Well, the current main branch (with your commits) works like a charm. Best to just close [my PR](https://github.com/echavet/MitsubishiCN105ESPHome/pull/80).

**Pull request merged**
